name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test Android Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  publish:
    name: Generate APK
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Save debug keystore
        run: echo $DEBUG_KEYSTORE | base64 -d > app/debug.keystore
        env:
          DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
          DEBUG_KEY: ${{ secrets.DEBUG_KEY }}
  device-test:
    runs-on: macos-latest
    name: Android Device Test Runner
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Checkout all submodules
      run: git submodule update --init --recursive
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: List Available Android Devices
      run: $ANDROID_HOME/tools/bin/avdmanager list
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: 28
        target: google_apis
        profile: 'pixel_xl'
        arch: x86_64
        script: ./gradlew connectedAndroidTest
